apiVersion: kubebuilder.zq.com/v1beta1
kind: MyDeployment
metadata:
  labels:
    app.kubernetes.io/name: mydeployment
    app.kubernetes.io/managed-by: kustomize
  name: mydeployment-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
        - image: nginx:v1.13
          name: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

